jobs:

  build-ios:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
        with:
          cache: false
          channel: any
          flutter-version: 3.35.2
      - run: sudo xcode-select -switch /Applications/Xcode_16.4.app
      - run: flutter build ios --debug --no-codesign

'on':
  push:
    branches:
      - main
